licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "datagram_to_vector_task",
    srcs = ["datagram_to_vector_task.cc"],
    deps = [
        "//dni/framework",
        "@fmtlib",
        "@spdlog",
    ],
    alwayslink = 1,
)
