cc_binary(
    name = "async",
    srcs = ["async.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "composing",
    srcs = ["composing.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "custom_graph",
    srcs = ["custom_graph.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "conditional_tasking",
    srcs = ["conditional_tasking.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "looping",
    srcs = ["looping.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "control_flow",
    srcs = ["control_flow.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "subflow",
    srcs = ["subflow.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "subflow_joining",
    srcs = ["subflow_joining.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "subflow_detaching",
    srcs = ["subflow_detaching.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "executing",
    srcs = ["executing.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "parallelism",
    srcs = ["parallelism.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "pipeline",
    srcs = ["pipeline.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "runtime_scheduling",
    srcs = ["runtime_scheduling.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "runtime_executor",
    srcs = ["runtime_executor.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "runtime_corun",
    srcs = ["runtime_corun.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "basic",
    srcs = ["basic.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "static_tasking",
    srcs = ["static_tasking.cc"],
    deps = ["@taskflow"],
)

cc_binary(
    name = "subgraph",
    srcs = ["subgraph.cc"],
    deps = ["@taskflow"],
)
