licenses(["notice"])

cc_binary(
    name = "transparent_task_test",
    srcs = ["transparent_task_test.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:transparent_task",
        "@spdlog",
    ],
)

cc_binary(
    name = "counter",
    srcs = ["counter.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:counter_task",
        "@fmtlib",
        "@spdlog",
    ],
)

cc_binary(
    name = "max",
    srcs = ["max.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:max_task",
        "@fmtlib",
        "@spdlog",
    ],
)

cc_binary(
    name = "sum",
    srcs = ["sum.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:sum_task",
        "@fmtlib",
        "@spdlog",
    ],
)

cc_binary(
    name = "threshold",
    srcs = ["threshold.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:threshold_task",
        "@fmtlib",
        "@spdlog",
    ],
)

cc_binary(
    name = "cond_threshold",
    srcs = ["cond_threshold.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:cond_threshold_task",
        "@fmtlib",
        "@spdlog",
    ],
)
