# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddos_detection_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ddos_detection_config.proto',
  package='ddos_detection_config',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x64\x64os_detection_config.proto\x12\x15\x64\x64os_detection_config\"#\n\x0bInputStream\x12\x14\n\x0cinput_stream\x18\x01 \x03(\t\"%\n\x0cOutputStream\x12\x15\n\routput_stream\x18\x01 \x03(\t\"E\n\x04Node\x12\x10\n\x08\x65xecutor\x18\x01 \x01(\t\x12\x14\n\x0cinput_stream\x18\x02 \x03(\t\x12\x15\n\routput_stream\x18\x03 \x03(\t\"\xb6\x01\n\x13\x44\x44oSDetectionConfig\x12\x38\n\x0cinput_stream\x18\x01 \x01(\x0b\x32\".ddos_detection_config.InputStream\x12:\n\routput_stream\x18\x02 \x01(\x0b\x32#.ddos_detection_config.OutputStream\x12)\n\x04node\x18\x03 \x03(\x0b\x32\x1b.ddos_detection_config.Nodeb\x06proto3')
)




_INPUTSTREAM = _descriptor.Descriptor(
  name='InputStream',
  full_name='ddos_detection_config.InputStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_stream', full_name='ddos_detection_config.InputStream.input_stream', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=89,
)


_OUTPUTSTREAM = _descriptor.Descriptor(
  name='OutputStream',
  full_name='ddos_detection_config.OutputStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_stream', full_name='ddos_detection_config.OutputStream.output_stream', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=128,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='ddos_detection_config.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executor', full_name='ddos_detection_config.Node.executor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_stream', full_name='ddos_detection_config.Node.input_stream', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_stream', full_name='ddos_detection_config.Node.output_stream', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=199,
)


_DDOSDETECTIONCONFIG = _descriptor.Descriptor(
  name='DDoSDetectionConfig',
  full_name='ddos_detection_config.DDoSDetectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_stream', full_name='ddos_detection_config.DDoSDetectionConfig.input_stream', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_stream', full_name='ddos_detection_config.DDoSDetectionConfig.output_stream', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='ddos_detection_config.DDoSDetectionConfig.node', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=384,
)

_DDOSDETECTIONCONFIG.fields_by_name['input_stream'].message_type = _INPUTSTREAM
_DDOSDETECTIONCONFIG.fields_by_name['output_stream'].message_type = _OUTPUTSTREAM
_DDOSDETECTIONCONFIG.fields_by_name['node'].message_type = _NODE
DESCRIPTOR.message_types_by_name['InputStream'] = _INPUTSTREAM
DESCRIPTOR.message_types_by_name['OutputStream'] = _OUTPUTSTREAM
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['DDoSDetectionConfig'] = _DDOSDETECTIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputStream = _reflection.GeneratedProtocolMessageType('InputStream', (_message.Message,), dict(
  DESCRIPTOR = _INPUTSTREAM,
  __module__ = 'ddos_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:ddos_detection_config.InputStream)
  ))
_sym_db.RegisterMessage(InputStream)

OutputStream = _reflection.GeneratedProtocolMessageType('OutputStream', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTSTREAM,
  __module__ = 'ddos_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:ddos_detection_config.OutputStream)
  ))
_sym_db.RegisterMessage(OutputStream)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'ddos_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:ddos_detection_config.Node)
  ))
_sym_db.RegisterMessage(Node)

DDoSDetectionConfig = _reflection.GeneratedProtocolMessageType('DDoSDetectionConfig', (_message.Message,), dict(
  DESCRIPTOR = _DDOSDETECTIONCONFIG,
  __module__ = 'ddos_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:ddos_detection_config.DDoSDetectionConfig)
  ))
_sym_db.RegisterMessage(DDoSDetectionConfig)


# @@protoc_insertion_point(module_scope)
