licenses(["notice"])

cc_binary(
    name = "transparent_task_test",
    srcs = ["transparent_task_test.cc"],
    deps = [
        "//dni/framework",
        "//dni/tasks/core:transparent_task",
        "@spdlog",
    ],
)
