#!/bin/bash

sudo tar -zxvf /usr/local/dni.tar.gz  -C /usr/local/    > /dev/null 2>&1
rm -f /usr/local/dni.tar.gz

sudo chmod 777 /etc/systemd/system
sudo cp /usr/local/dni/dni.service.in /etc/systemd/system/dni.service
sudo chmod 644 /etc/systemd/system/dni.service

#sudo rm -f /usr/bin/dnictl 
#sudo ln -s /usr/local/dni/dnictl /usr/bin/dnictl


#dnictl completion bash > cobra_completion
#sudo mkdir -p  /etc/bash_completion.d/
#sudo mv cobra_completion /etc/bash_completion.d/
 
sudo systemctl daemon-reload
sudo systemctl start dni.service
sudo systemctl status dni.service
sudo systemctl enable dni.service